In [24]:
import pandas as pd
import numpy as np

In [25]:
file_path = 'C:\\Users\\ACER\\Downloads\\DS307\\DeepInf-master\\DeepInf-master\\src\\DeepInf\\twitter\\twitter\\adjacency_matrix.npy'

# Đọc file
array = np.load(file_path)
array

array([[[0., 0., 0., ..., 0., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 1., 0., 0.]],

       [[0., 0., 0., ..., 0., 1., 1.],
        [0., 0., 1., ..., 0., 1., 1.],
        [0., 1., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [1., 1., 0., ..., 0., 0., 1.],
        [1., 1., 1., ..., 1., 1., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0.

In [26]:
array[1].shape[0]

50

In [27]:
file_path = 'C:\\Users\\ACER\\Downloads\\DS307\\DeepInf-master\\DeepInf-master\\src\\DeepInf\\twitter\\twitter\\vertex_id.npy'

# Đọc file
array = np.load(file_path)
array

array([[ 79490, 143235,  67076, ..., 143229,  93822, 143215],
       [ 91137, 291969,  49415, ..., 246516,  10109,  87167],
       [  3521,  20054,  80770, ...,  19723,  20021,  20877],
       ...,
       [ 30465,      7,  61321, ..., 162810,  28539,  35533],
       [277890,  41475, 100228, ..., 126194, 109307, 136484],
       [ 33410,   6407,  30985, ..., 290684, 107903, 226666]], dtype=int64)

In [28]:
array[1].shape[0]

50

In [3]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1+cpu
False


In [29]:
file_path = 'C:\\Users\\ACER\\Downloads\\DS307\\DeepInf-master\\DeepInf-master\\src\\DeepInf\\twitter\\twitter\\influence_feature.npy'

# Đọc file
array = np.load(file_path)
array

array([[[0., 0.],
        [0., 0.],
        [1., 0.],
        ...,
        [0., 0.],
        [1., 0.],
        [0., 1.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [0., 0.],
        [0., 1.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [0., 1.]],

       ...,

       [[0., 0.],
        [0., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [0., 0.],
        [0., 1.]],

       [[1., 0.],
        [1., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [1., 0.],
        [0., 1.]]], dtype=float32)

In [30]:
array[1].shape[0]

50

In [31]:
file_path = 'C:\\Users\\ACER\\Downloads\\DS307\\DeepInf-master\\DeepInf-master\\src\\DeepInf\\twitter\\twitter\\label.npy'

# Đọc file
array = np.load(file_path)
array

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
array[1]

0

In [33]:
file_path = 'C:\\Users\\ACER\\Downloads\\DS307\\DeepInf-master\\DeepInf-master\\src\\DeepInf\\twitter\\twitter\\vertex_feature.npy'

# Đọc file
array = np.load(file_path)
array

array([[6.13609867e-05, 1.79986203e-06, 8.71131330e-03, ...,
        1.14512945e-02, 1.14512945e-02, 9.60000000e+01],
       [2.11505922e-04, 6.50876253e-03, 1.54530949e-04, ...,
        1.16933430e-01, 1.16933430e-01, 1.25000000e+02],
       [6.75675676e-03, 1.02316602e-01, 5.10252917e-06, ...,
        4.35673703e-03, 4.35673703e-03, 7.90000000e+01],
       ...,
       [1.00000000e+00, 0.00000000e+00, 3.28490579e-07, ...,
        7.02992187e-18, 7.93136822e-19, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 3.28490579e-07, ...,
        7.02992187e-18, 7.93136822e-19, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 3.28490579e-07, ...,
        7.02992187e-18, 7.93136822e-19, 0.00000000e+00]])

In [34]:
array[1].shape[0]

7

In [35]:
file_path = 'C:\\Users\\ACER\\Downloads\\DS307\\DeepInf-master\\DeepInf-master\\src\\DeepInf\\twitter\\twitter\\vertex_id.npy'

# Đọc file
array = np.load(file_path)
array

array([[ 79490, 143235,  67076, ..., 143229,  93822, 143215],
       [ 91137, 291969,  49415, ..., 246516,  10109,  87167],
       [  3521,  20054,  80770, ...,  19723,  20021,  20877],
       ...,
       [ 30465,      7,  61321, ..., 162810,  28539,  35533],
       [277890,  41475, 100228, ..., 126194, 109307, 136484],
       [ 33410,   6407,  30985, ..., 290684, 107903, 226666]], dtype=int64)

In [36]:
array[1].shape[0]

50